# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf7d8b7014a53639344bfc579f62cd70007d676b3b1213a634a0a06ff5a3a9eda47cb8d53922dbf8c6411c9760e3c918ecbf67f9de0a2359eaa0feaf4ddc1dac

test:
  secret_key_base: 9b3cd4c146f10468cdf14611c27091cef876203be6ce8f3a8053485813b4208ea96b34c0f955c5ad1932b3282b7a9dd4f6eef7d0405ee93fe6e5b36caa43bca9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
